const fs = require('fs');
const path = require('path');

function write(filePath, content) {
  const dir = path.dirname(filePath);
  if (dir !== '.') fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Created: ' + filePath);
}

// Chat Screen
write('src/screens/ChatScreen.js', [
  "import React, { useState } from 'react';",
  "import { View, Text, StyleSheet, FlatList, TextInput, TouchableOpacity, KeyboardAvoidingView, Platform } from 'react-native';",
  "",
  "export default function ChatScreen({ profile, onBack }) {",
  "  const [messages, setMessages] = useState([",
  "    { id: '1', text: 'Hey! Saw we matched. Your profile looks great!', from: 'them', time: '2:30 PM' },",
  "    { id: '2', text: 'Thanks! Your place sounds amazing. What area are you looking in?', from: 'me', time: '2:31 PM' },",
  "    { id: '3', text: 'Mostly around ' + profile.location + '. Budget is flexible too.', from: 'them', time: '2:32 PM' },",
  "  ]);",
  "  const [input, setInput] = useState('');",
  "",
  "  const sendMessage = () => {",
  "    if (!input.trim()) return;",
  "    const newMsg = { id: Date.now().toString(), text: input.trim(), from: 'me', time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) };",
  "    setMessages(prev => [...prev, newMsg]);",
  "    setInput('');",
  "  };",
  "",
  "  return (",
  "    <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>",
  "      <View style={styles.header}>",
  "        <TouchableOpacity onPress={onBack} style={styles.backBtn}>",
  "          <Text style={styles.backText}>Back</Text>",
  "        </TouchableOpacity>",
  "        <View style={[styles.headerAvatar, { backgroundColor: profile.color }]}>",
  "          <Text style={styles.headerEmoji}>{profile.emoji}</Text>",
  "        </View>",
  "        <View>",
  "          <Text style={styles.headerName}>{profile.name}</Text>",
  "          <Text style={styles.headerSub}>{profile.location}</Text>",
  "        </View>",
  "      </View>",
  "",
  "      <FlatList",
  "        data={messages}",
  "        keyExtractor={item => item.id}",
  "        contentContainerStyle={styles.messageList}",
  "        renderItem={({ item }) => (",
  "          <View style={[styles.messageBubble, item.from === 'me' ? styles.myBubble : styles.theirBubble]}>",
  "            <Text style={[styles.messageText, item.from === 'me' ? styles.myText : styles.theirText]}>{item.text}</Text>",
  "            <Text style={styles.timeText}>{item.time}</Text>",
  "          </View>",
  "        )}",
  "      />",
  "",
  "      <View style={styles.inputRow}>",
  "        <TextInput",
  "          style={styles.input}",
  "          value={input}",
  "          onChangeText={setInput}",
  "          placeholder='Message...'",
  "          placeholderTextColor='#aaa'",
  "          returnKeyType='send'",
  "          onSubmitEditing={sendMessage}",
  "        />",
  "        <TouchableOpacity style={styles.sendBtn} onPress={sendMessage}>",
  "          <Text style={styles.sendText}>Send</Text>",
  "        </TouchableOpacity>",
  "      </View>",
  "    </KeyboardAvoidingView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  header: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, backgroundColor: '#fff', borderBottomWidth: 0.5, borderBottomColor: '#e5e5e5' },",
  "  backBtn: { marginRight: 4 },",
  "  backText: { fontSize: 16, color: '#534AB7', fontWeight: '500' },",
  "  headerAvatar: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },",
  "  headerEmoji: { fontSize: 20 },",
  "  headerName: { fontSize: 16, fontWeight: '600', color: '#1a1a1a' },",
  "  headerSub: { fontSize: 12, color: '#888' },",
  "  messageList: { padding: 16, gap: 10 },",
  "  messageBubble: { maxWidth: '75%', padding: 12, borderRadius: 18, gap: 4 },",
  "  myBubble: { backgroundColor: '#534AB7', alignSelf: 'flex-end', borderBottomRightRadius: 4 },",
  "  theirBubble: { backgroundColor: '#fff', alignSelf: 'flex-start', borderBottomLeftRadius: 4, borderWidth: 0.5, borderColor: '#e5e5e5' },",
  "  messageText: { fontSize: 15, lineHeight: 21 },",
  "  myText: { color: '#fff' },",
  "  theirText: { color: '#1a1a1a' },",
  "  timeText: { fontSize: 10, color: 'rgba(255,255,255,0.6)', alignSelf: 'flex-end' },",
  "  inputRow: { flexDirection: 'row', gap: 10, padding: 12, paddingBottom: 32, backgroundColor: '#fff', borderTopWidth: 0.5, borderTopColor: '#e5e5e5' },",
  "  input: { flex: 1, backgroundColor: '#f5f5f5', borderRadius: 24, paddingHorizontal: 16, paddingVertical: 10, fontSize: 15, color: '#1a1a1a' },",
  "  sendBtn: { backgroundColor: '#534AB7', borderRadius: 24, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center' },",
  "  sendText: { color: '#fff', fontWeight: '600', fontSize: 14 },",
  "});",
].join('\n'));

// Updated MatchesScreen with navigation to chat
write('src/screens/MatchesScreen.js', [
  "import React, { useState } from 'react';",
  "import { View, Text, FlatList, StyleSheet, TouchableOpacity } from 'react-native';",
  "import ChatScreen from './ChatScreen';",
  "",
  "export default function MatchesScreen({ matches }) {",
  "  const [activeChat, setActiveChat] = useState(null);",
  "",
  "  if (activeChat) {",
  "    return <ChatScreen profile={activeChat} onBack={() => setActiveChat(null)} />;",
  "  }",
  "",
  "  if (matches.length === 0) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <Text style={styles.emptyTitle}>No matches yet</Text>",
  "        <Text style={styles.emptySub}>Start swiping to find your roommate</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <Text style={styles.header}>Matches</Text>",
  "      <FlatList data={matches} keyExtractor={(item) => item.id} contentContainerStyle={styles.list}",
  "        renderItem={({ item }) => (",
  "          <TouchableOpacity style={styles.matchItem} activeOpacity={0.7} onPress={() => setActiveChat(item)}>",
  "            <View style={[styles.avatar, { backgroundColor: item.color }]}>",
  "              <Text style={styles.avatarEmoji}>{item.emoji}</Text>",
  "            </View>",
  "            <View style={styles.info}>",
  "              <View style={styles.nameRow}>",
  "                <Text style={styles.name}>{item.name}</Text>",
  "                <View style={styles.badge}><Text style={styles.badgeText}>New match</Text></View>",
  "              </View>",
  "              <Text style={styles.sub}>{item.role}</Text>",
  "              <Text style={styles.sub}>{item.location} - {item.budget}</Text>",
  "            </View>",
  "            <Text style={styles.arrow}>›</Text>",
  "          </TouchableOpacity>",
  "        )}",
  "      />",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  header: { fontSize: 22, fontWeight: '700', color: '#534AB7', paddingTop: 56, paddingBottom: 16, paddingHorizontal: 20 },",
  "  list: { paddingHorizontal: 16, gap: 10 },",
  "  matchItem: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16, padding: 14, alignItems: 'center', gap: 14, borderWidth: 0.5, borderColor: '#e8e8e8' },",
  "  avatar: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },",
  "  avatarEmoji: { fontSize: 26 },",
  "  info: { flex: 1, gap: 3 },",
  "  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },",
  "  name: { fontSize: 16, fontWeight: '600', color: '#1a1a1a' },",
  "  badge: { backgroundColor: '#EEEDFE', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },",
  "  badgeText: { fontSize: 11, color: '#534AB7', fontWeight: '500' },",
  "  sub: { fontSize: 13, color: '#666' },",
  "  arrow: { fontSize: 22, color: '#ccc' },",
  "  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f7ff', gap: 10 },",
  "  emptyTitle: { fontSize: 20, fontWeight: '600', color: '#1a1a1a' },",
  "  emptySub: { fontSize: 14, color: '#888' },",
  "});",
].join('\n'));

console.log('\nChat feature added! The app will reload automatically.');
