const fs = require('fs');
const path = require('path');

function write(filePath, content) {
  const dir = path.dirname(filePath);
  if (dir !== '.') fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Created: ' + filePath);
}

// Onboarding Screen
write('src/screens/OnboardingScreen.js', [
  "import React, { useState } from 'react';",
  "import { View, Text, StyleSheet, TextInput, TouchableOpacity, ScrollView } from 'react-native';",
  "",
  "const STEPS = ['Welcome', 'Name', 'Role', 'Location', 'Budget', 'Lifestyle', 'Bio'];",
  "",
  "export default function OnboardingScreen({ onComplete }) {",
  "  const [step, setStep] = useState(0);",
  "  const [profile, setProfile] = useState({",
  "    name: '', role: '', location: '', budget: '', lifestyle: 'Flexible', smoking: 'Non-smoker', pets: 'No preference', bio: '',",
  "  });",
  "",
  "  const update = (key, value) => setProfile(prev => ({ ...prev, [key]: value }));",
  "",
  "  const next = () => {",
  "    if (step < STEPS.length - 1) setStep(s => s + 1);",
  "    else onComplete({ ...profile, id: 'me', emoji: '🧑', color: '#EEEDFE', age: 25, tags: [profile.lifestyle, profile.smoking, profile.pets] });",
  "  };",
  "",
  "  const back = () => setStep(s => s - 1);",
  "",
  "  const renderStep = () => {",
  "    switch (step) {",
  "      case 0: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.bigEmoji}>🏠</Text>",
  "          <Text style={styles.title}>Welcome to RoomieMatch</Text>",
  "          <Text style={styles.subtitle}>Find your perfect roommate in a few steps.</Text>",
  "        </View>",
  "      );",
  "      case 1: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>What is your name?</Text>",
  "          <TextInput style={styles.input} placeholder='Your name' placeholderTextColor='#aaa' value={profile.name} onChangeText={v => update('name', v)} autoFocus />",
  "        </View>",
  "      );",
  "      case 2: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>What do you do?</Text>",
  "          <TextInput style={styles.input} placeholder='e.g. Software Engineer, Student' placeholderTextColor='#aaa' value={profile.role} onChangeText={v => update('role', v)} autoFocus />",
  "        </View>",
  "      );",
  "      case 3: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>Where are you looking?</Text>",
  "          <TextInput style={styles.input} placeholder='e.g. Boston, MA' placeholderTextColor='#aaa' value={profile.location} onChangeText={v => update('location', v)} autoFocus />",
  "        </View>",
  "      );",
  "      case 4: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>What is your budget?</Text>",
  "          <TextInput style={styles.input} placeholder='e.g. $1,200-$1,600/mo' placeholderTextColor='#aaa' value={profile.budget} onChangeText={v => update('budget', v)} autoFocus />",
  "        </View>",
  "      );",
  "      case 5: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>What is your lifestyle?</Text>",
  "          {['Early bird', 'Night owl', 'Flexible'].map(opt => (",
  "            <TouchableOpacity key={opt} style={[styles.optionBtn, profile.lifestyle === opt && styles.optionBtnActive]} onPress={() => update('lifestyle', opt)}>",
  "              <Text style={[styles.optionText, profile.lifestyle === opt && styles.optionTextActive]}>{opt}</Text>",
  "            </TouchableOpacity>",
  "          ))}",
  "          <Text style={[styles.title, { marginTop: 24 }]}>Smoking?</Text>",
  "          {['Non-smoker', 'Smoker', 'No preference'].map(opt => (",
  "            <TouchableOpacity key={opt} style={[styles.optionBtn, profile.smoking === opt && styles.optionBtnActive]} onPress={() => update('smoking', opt)}>",
  "              <Text style={[styles.optionText, profile.smoking === opt && styles.optionTextActive]}>{opt}</Text>",
  "            </TouchableOpacity>",
  "          ))}",
  "          <Text style={[styles.title, { marginTop: 24 }]}>Pets?</Text>",
  "          {['No preference', 'Has pets', 'No pets'].map(opt => (",
  "            <TouchableOpacity key={opt} style={[styles.optionBtn, profile.pets === opt && styles.optionBtnActive]} onPress={() => update('pets', opt)}>",
  "              <Text style={[styles.optionText, profile.pets === opt && styles.optionTextActive]}>{opt}</Text>",
  "            </TouchableOpacity>",
  "          ))}",
  "        </View>",
  "      );",
  "      case 6: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>Tell people about yourself</Text>",
  "          <TextInput style={[styles.input, styles.bioInput]} placeholder='e.g. Grad student, love cooking, looking for a chill roommate...' placeholderTextColor='#aaa' value={profile.bio} onChangeText={v => update('bio', v)} multiline autoFocus />",
  "        </View>",
  "      );",
  "    }",
  "  };",
  "",
  "  const isNextDisabled = () => {",
  "    if (step === 1 && !profile.name.trim()) return true;",
  "    if (step === 2 && !profile.role.trim()) return true;",
  "    if (step === 3 && !profile.location.trim()) return true;",
  "    if (step === 4 && !profile.budget.trim()) return true;",
  "    return false;",
  "  };",
  "",
  "  return (",
  "    <ScrollView style={styles.container} contentContainerStyle={styles.content} keyboardShouldPersistTaps='handled'>",
  "      <View style={styles.progressRow}>",
  "        {STEPS.map((_, i) => (",
  "          <View key={i} style={[styles.progressDot, i <= step && styles.progressDotActive]} />",
  "        ))}",
  "      </View>",
  "      {renderStep()}",
  "      <View style={styles.btnRow}>",
  "        {step > 0 && (",
  "          <TouchableOpacity style={styles.backBtn} onPress={back}>",
  "            <Text style={styles.backBtnText}>Back</Text>",
  "          </TouchableOpacity>",
  "        )}",
  "        <TouchableOpacity style={[styles.nextBtn, isNextDisabled() && styles.nextBtnDisabled]} onPress={next} disabled={isNextDisabled()}>",
  "          <Text style={styles.nextBtnText}>{step === STEPS.length - 1 ? 'Get Started' : 'Next'}</Text>",
  "        </TouchableOpacity>",
  "      </View>",
  "    </ScrollView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  content: { padding: 24, paddingTop: 60, minHeight: '100%' },",
  "  progressRow: { flexDirection: 'row', gap: 6, marginBottom: 40 },",
  "  progressDot: { flex: 1, height: 4, borderRadius: 2, backgroundColor: '#e0e0e0' },",
  "  progressDotActive: { backgroundColor: '#534AB7' },",
  "  stepContainer: { flex: 1, gap: 16 },",
  "  bigEmoji: { fontSize: 64, textAlign: 'center', marginBottom: 8 },",
  "  title: { fontSize: 24, fontWeight: '700', color: '#1a1a1a' },",
  "  subtitle: { fontSize: 16, color: '#666', lineHeight: 24 },",
  "  input: { backgroundColor: '#fff', borderRadius: 12, padding: 16, fontSize: 16, color: '#1a1a1a', borderWidth: 0.5, borderColor: '#e0e0e0' },",
  "  bioInput: { height: 120, textAlignVertical: 'top' },",
  "  optionBtn: { backgroundColor: '#fff', borderRadius: 12, padding: 16, borderWidth: 0.5, borderColor: '#e0e0e0' },",
  "  optionBtnActive: { backgroundColor: '#534AB7', borderColor: '#534AB7' },",
  "  optionText: { fontSize: 16, color: '#1a1a1a', fontWeight: '500' },",
  "  optionTextActive: { color: '#fff' },",
  "  btnRow: { flexDirection: 'row', gap: 12, marginTop: 40, paddingBottom: 40 },",
  "  backBtn: { flex: 1, padding: 16, borderRadius: 12, borderWidth: 0.5, borderColor: '#e0e0e0', alignItems: 'center' },",
  "  backBtnText: { fontSize: 16, color: '#666', fontWeight: '500' },",
  "  nextBtn: { flex: 2, padding: 16, borderRadius: 12, backgroundColor: '#534AB7', alignItems: 'center' },",
  "  nextBtnDisabled: { backgroundColor: '#ccc' },",
  "  nextBtnText: { fontSize: 16, color: '#fff', fontWeight: '600' },",
  "});",
].join('\n'));

// Updated app/index.tsx to handle onboarding state
write('app/index.tsx', [
  "import { useState } from 'react';",
  "import TabNavigator from '../src/navigation/TabNavigator';",
  "import OnboardingScreen from '../src/screens/OnboardingScreen';",
  "",
  "export default function Index() {",
  "  const [userProfile, setUserProfile] = useState(null);",
  "",
  "  if (!userProfile) {",
  "    return <OnboardingScreen onComplete={(profile) => setUserProfile(profile)} />;",
  "  }",
  "",
  "  return <TabNavigator userProfile={userProfile} />;",
  "}",
].join('\n'));

// Updated TabNavigator to accept and pass userProfile
write('src/navigation/TabNavigator.js', [
  "import React, { useState } from 'react';",
  "import { View, TouchableOpacity, Text, StyleSheet } from 'react-native';",
  "import DiscoverScreen from '../screens/DiscoverScreen';",
  "import MatchesScreen from '../screens/MatchesScreen';",
  "import ProfileScreen from '../screens/ProfileScreen';",
  "",
  "const TABS = [",
  "  { id: 'discover', label: 'Discover', icon: 'D' },",
  "  { id: 'matches', label: 'Matches', icon: 'M' },",
  "  { id: 'profile', label: 'Profile', icon: 'P' },",
  "];",
  "",
  "export default function TabNavigator({ userProfile }) {",
  "  const [activeTab, setActiveTab] = useState('discover');",
  "  const [matches, setMatches] = useState([]);",
  "",
  "  const handleMatch = (profile) => {",
  "    setMatches(prev => prev.find(m => m.id === profile.id) ? prev : [profile, ...prev]);",
  "  };",
  "",
  "  const renderScreen = () => {",
  "    switch (activeTab) {",
  "      case 'discover': return <DiscoverScreen onMatch={handleMatch} />;",
  "      case 'matches': return <MatchesScreen matches={matches} />;",
  "      case 'profile': return <ProfileScreen userProfile={userProfile} />;",
  "    }",
  "  };",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <View style={styles.screenArea}>{renderScreen()}</View>",
  "      <View style={styles.tabBar}>",
  "        {TABS.map(tab => {",
  "          const isActive = activeTab === tab.id;",
  "          const showBadge = tab.id === 'matches' && matches.length > 0;",
  "          return (",
  "            <TouchableOpacity key={tab.id} style={styles.tab} onPress={() => setActiveTab(tab.id)} activeOpacity={0.7}>",
  "              <View style={styles.iconWrapper}>",
  "                <Text style={[styles.icon, isActive && styles.iconActive]}>{tab.icon}</Text>",
  "                {showBadge && <View style={styles.badge}><Text style={styles.badgeText}>{matches.length}</Text></View>}",
  "              </View>",
  "              <Text style={[styles.tabLabel, isActive && styles.tabLabelActive]}>{tab.label}</Text>",
  "            </TouchableOpacity>",
  "          );",
  "        })}",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  screenArea: { flex: 1 },",
  "  tabBar: { flexDirection: 'row', backgroundColor: '#fff', borderTopWidth: 0.5, borderTopColor: '#e5e5e5', paddingBottom: 20 },",
  "  tab: { flex: 1, alignItems: 'center', paddingTop: 10, paddingBottom: 4, gap: 3 },",
  "  iconWrapper: { position: 'relative' },",
  "  icon: { fontSize: 20, color: '#aaa' },",
  "  iconActive: { color: '#534AB7' },",
  "  tabLabel: { fontSize: 11, color: '#aaa' },",
  "  tabLabelActive: { color: '#534AB7', fontWeight: '500' },",
  "  badge: { position: 'absolute', top: -4, right: -8, backgroundColor: '#534AB7', borderRadius: 8, minWidth: 16, height: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 },",
  "  badgeText: { fontSize: 10, color: '#fff', fontWeight: '600' },",
  "});",
].join('\n'));

// Updated ProfileScreen to show real user data
write('src/screens/ProfileScreen.js', [
  "import React from 'react';",
  "import { View, Text, ScrollView, StyleSheet } from 'react-native';",
  "",
  "export default function ProfileScreen({ userProfile }) {",
  "  const p = userProfile || {};",
  "  return (",
  "    <ScrollView style={styles.container} contentContainerStyle={styles.content}>",
  "      <Text style={styles.header}>My Profile</Text>",
  "      <View style={styles.avatarSection}>",
  "        <View style={styles.avatar}><Text style={styles.avatarEmoji}>🧑</Text></View>",
  "        <Text style={styles.name}>{p.name || 'Your Name'}</Text>",
  "        <Text style={styles.sub}>{p.location || 'Your Location'} - {p.role || 'Your Role'}</Text>",
  "      </View>",
  "      <View style={styles.section}>",
  "        <Text style={styles.sectionTitle}>MY PREFERENCES</Text>",
  "        {[['Budget', p.budget || '-'], ['Lifestyle', p.lifestyle || '-'], ['Pets', p.pets || '-'], ['Smoking', p.smoking || '-']].map(([label, value], i, arr) => (",
  "          <View key={label} style={[styles.prefRow, i === arr.length - 1 && { borderBottomWidth: 0 }]}>",
  "            <Text style={styles.prefLabel}>{label}</Text>",
  "            <Text style={styles.prefValue}>{value}</Text>",
  "          </View>",
  "        ))}",
  "      </View>",
  "      <View style={styles.section}>",
  "        <Text style={styles.sectionTitle}>ABOUT ME</Text>",
  "        <Text style={styles.bio}>{p.bio || 'No bio yet.'}</Text>",
  "      </View>",
  "    </ScrollView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  content: { paddingBottom: 40 },",
  "  header: { fontSize: 22, fontWeight: '700', color: '#534AB7', paddingTop: 56, paddingBottom: 20, paddingHorizontal: 20 },",
  "  avatarSection: { alignItems: 'center', marginBottom: 24, gap: 6 },",
  "  avatar: { width: 90, height: 90, borderRadius: 45, backgroundColor: '#EEEDFE', alignItems: 'center', justifyContent: 'center', marginBottom: 4 },",
  "  avatarEmoji: { fontSize: 46 },",
  "  name: { fontSize: 22, fontWeight: '600', color: '#1a1a1a' },",
  "  sub: { fontSize: 14, color: '#888' },",
  "  section: { backgroundColor: '#fff', marginHorizontal: 16, marginBottom: 14, borderRadius: 16, padding: 16, borderWidth: 0.5, borderColor: '#e8e8e8' },",
  "  sectionTitle: { fontSize: 11, fontWeight: '600', color: '#999', letterSpacing: 0.8, marginBottom: 12 },",
  "  prefRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 0.5, borderBottomColor: '#f0f0f0' },",
  "  prefLabel: { fontSize: 14, color: '#555' },",
  "  prefValue: { fontSize: 14, fontWeight: '500', color: '#1a1a1a' },",
  "  bio: { fontSize: 14, color: '#555', lineHeight: 22 },",
  "});",
].join('\n'));

console.log('\nOnboarding added! Run: npx expo start --clear');
