const fs = require('fs');

function write(filePath, content) {
  const dir = require('path').dirname(filePath);
  if (dir !== '.') require('fs').mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Created: ' + filePath);
}

// Hook to fetch real profiles from Supabase
write('src/hooks/useProfiles.js', [
  "import { useState, useEffect } from 'react';",
  "import { supabase } from '../lib/supabase';",
  "",
  "export default function useProfiles(currentUserId) {",
  "  const [profiles, setProfiles] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    if (!currentUserId) return;",
  "    supabase",
  "      .from('profiles')",
  "      .select('*')",
  "      .neq('id', currentUserId)",
  "      .then(({ data, error }) => {",
  "        if (error) console.log('Error fetching profiles:', error);",
  "        else setProfiles(data || []);",
  "        setLoading(false);",
  "      });",
  "  }, [currentUserId]);",
  "",
  "  return { profiles, loading };",
  "}",
].join('\n'));

// Updated DiscoverScreen using real profiles
write('src/screens/DiscoverScreen.js', [
  "import React, { useState, useRef } from 'react';",
  "import { View, Text, StyleSheet, Animated, PanResponder, TouchableOpacity, Dimensions, ActivityIndicator } from 'react-native';",
  "import ProfileCard from '../components/ProfileCard';",
  "import useProfiles from '../hooks/useProfiles';",
  "",
  "const SCREEN_WIDTH = Dimensions.get('window').width;",
  "const SWIPE_THRESHOLD = SCREEN_WIDTH * 0.25;",
  "",
  "export default function DiscoverScreen({ onMatch, userProfile }) {",
  "  const { profiles, loading } = useProfiles(userProfile?.id);",
  "  const [currentIndex, setCurrentIndex] = useState(0);",
  "  const position = useRef(new Animated.ValueXY()).current;",
  "",
  "  const panResponder = PanResponder.create({",
  "    onStartShouldSetPanResponder: () => true,",
  "    onPanResponderMove: (_, gesture) => { position.setValue({ x: gesture.dx, y: gesture.dy }); },",
  "    onPanResponderRelease: (_, gesture) => {",
  "      if (gesture.dx > SWIPE_THRESHOLD) swipeRight();",
  "      else if (gesture.dx < -SWIPE_THRESHOLD) swipeLeft();",
  "      else Animated.spring(position, { toValue: { x: 0, y: 0 }, useNativeDriver: false }).start();",
  "    },",
  "  });",
  "",
  "  const swipeRight = () => {",
  "    Animated.timing(position, { toValue: { x: SCREEN_WIDTH * 1.5, y: 0 }, duration: 300, useNativeDriver: false }).start(() => {",
  "      onMatch(profiles[currentIndex]);",
  "      nextCard();",
  "    });",
  "  };",
  "",
  "  const swipeLeft = () => {",
  "    Animated.timing(position, { toValue: { x: -SCREEN_WIDTH * 1.5, y: 0 }, duration: 300, useNativeDriver: false }).start(() => nextCard());",
  "  };",
  "",
  "  const nextCard = () => { position.setValue({ x: 0, y: 0 }); setCurrentIndex(i => i + 1); };",
  "",
  "  const rotate = position.x.interpolate({ inputRange: [-SCREEN_WIDTH / 2, 0, SCREEN_WIDTH / 2], outputRange: ['-10deg', '0deg', '10deg'], extrapolate: 'clamp' });",
  "  const likeOpacity = position.x.interpolate({ inputRange: [0, SWIPE_THRESHOLD], outputRange: [0, 1], extrapolate: 'clamp' });",
  "  const nopeOpacity = position.x.interpolate({ inputRange: [-SWIPE_THRESHOLD, 0], outputRange: [1, 0], extrapolate: 'clamp' });",
  "",
  "  if (loading) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <ActivityIndicator size='large' color='#534AB7' />",
  "        <Text style={styles.emptySub}>Finding roommates...</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  if (profiles.length === 0) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <Text style={styles.emptyTitle}>No roommates yet!</Text>",
  "        <Text style={styles.emptySub}>Share the app with friends to see profiles here.</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  if (currentIndex >= profiles.length) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <Text style={styles.emptyTitle}>You have seen everyone!</Text>",
  "        <Text style={styles.emptySub}>Check your matches tab</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <Text style={styles.header}>RoomieMatch</Text>",
  "      <View style={styles.cardContainer}>",
  "        {currentIndex + 1 < profiles.length && (",
  "          <View style={[styles.cardWrapper, styles.backCard]}>",
  "            <ProfileCard profile={profiles[currentIndex + 1]} userProfile={userProfile} />",
  "          </View>",
  "        )}",
  "        <Animated.View style={[styles.cardWrapper, { transform: [{ translateX: position.x }, { translateY: position.y }, { rotate }] }]} {...panResponder.panHandlers}>",
  "          <Animated.View style={[styles.stamp, styles.likeStamp, { opacity: likeOpacity }]}><Text style={styles.likeText}>LIKE</Text></Animated.View>",
  "          <Animated.View style={[styles.stamp, styles.nopeStamp, { opacity: nopeOpacity }]}><Text style={styles.nopeText}>NOPE</Text></Animated.View>",
  "          <ProfileCard profile={profiles[currentIndex]} userProfile={userProfile} />",
  "        </Animated.View>",
  "      </View>",
  "      <View style={styles.actions}>",
  "        <TouchableOpacity style={[styles.btn, styles.passBtn]} onPress={swipeLeft}><Text style={styles.passBtnText}>X</Text></TouchableOpacity>",
  "        <TouchableOpacity style={[styles.btn, styles.likeBtn]} onPress={swipeRight}><Text style={styles.likeBtnText}>Like</Text></TouchableOpacity>",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  header: { fontSize: 22, fontWeight: '700', color: '#534AB7', textAlign: 'center', paddingTop: 56, paddingBottom: 12 },",
  "  cardContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },",
  "  cardWrapper: { position: 'absolute', width: '100%' },",
  "  backCard: { transform: [{ scale: 0.95 }, { translateY: 12 }] },",
  "  stamp: { position: 'absolute', top: 24, zIndex: 10, paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8, borderWidth: 3 },",
  "  likeStamp: { left: 20, borderColor: '#1D9E75', backgroundColor: 'rgba(29,158,117,0.1)' },",
  "  likeText: { fontSize: 22, fontWeight: '800', color: '#1D9E75', letterSpacing: 2 },",
  "  nopeStamp: { right: 20, borderColor: '#E24B4A', backgroundColor: 'rgba(226,75,74,0.1)' },",
  "  nopeText: { fontSize: 22, fontWeight: '800', color: '#E24B4A', letterSpacing: 2 },",
  "  actions: { flexDirection: 'row', justifyContent: 'center', gap: 24, paddingVertical: 20, paddingBottom: 32 },",
  "  btn: { width: 60, height: 60, borderRadius: 30, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 3 },",
  "  passBtn: { backgroundColor: '#fff', borderWidth: 0.5, borderColor: '#ddd' },",
  "  passBtnText: { fontSize: 20, color: '#E24B4A', fontWeight: '700' },",
  "  likeBtn: { backgroundColor: '#f0eefe', borderWidth: 0.5, borderColor: '#AFA9EC' },",
  "  likeBtnText: { fontSize: 16, color: '#534AB7', fontWeight: '700' },",
  "  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f7ff', gap: 10, padding: 32 },",
  "  emptyTitle: { fontSize: 20, fontWeight: '600', color: '#1a1a1a', textAlign: 'center' },",
  "  emptySub: { fontSize: 14, color: '#888', textAlign: 'center' },",
  "});",
].join('\n'));

// Updated ProfileCard to handle real profiles (no hardcoded emoji/color assumptions)
write('src/components/ProfileCard.js', [
  "import React from 'react';",
  "import { View, Text, StyleSheet } from 'react-native';",
  "",
  "export default function ProfileCard({ profile }) {",
  "  const color = profile.color || '#EEEDFE';",
  "  const emoji = profile.emoji || '🧑';",
  "",
  "  return (",
  "    <View style={styles.card}>",
  "      <View style={[styles.avatarBox, { backgroundColor: color }]}>",
  "        <Text style={styles.avatarEmoji}>{emoji}</Text>",
  "      </View>",
  "      <View style={styles.body}>",
  "        <Text style={styles.name}>{profile.name}{profile.age ? ', ' + profile.age : ''}</Text>",
  "        <Text style={styles.sub}>{profile.role}</Text>",
  "        <Text style={styles.sub}>{profile.location}</Text>",
  "        <Text style={styles.budget}>{profile.budget}</Text>",
  "        {profile.tags && profile.tags.length > 0 && (",
  "          <View style={styles.tags}>",
  "            {profile.tags.map((tag, i) => (",
  "              <View key={i} style={styles.tag}>",
  "                <Text style={styles.tagText}>{tag}</Text>",
  "              </View>",
  "            ))}",
  "          </View>",
  "        )}",
  "        <Text style={styles.bio}>{profile.bio}</Text>",
  "        <View style={styles.details}>",
  "          {[['Lifestyle', profile.lifestyle], ['Smoking', profile.smoking], ['Pets', profile.pets]].filter(([, v]) => v).map(([label, value]) => (",
  "            <View key={label} style={styles.detailRow}>",
  "              <Text style={styles.detailLabel}>{label}</Text>",
  "              <Text style={styles.detailValue}>{value}</Text>",
  "            </View>",
  "          ))}",
  "        </View>",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  card: { backgroundColor: '#fff', borderRadius: 20, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 4 },",
  "  avatarBox: { height: 180, alignItems: 'center', justifyContent: 'center' },",
  "  avatarEmoji: { fontSize: 72 },",
  "  body: { padding: 18 },",
  "  name: { fontSize: 22, fontWeight: '600', color: '#1a1a1a' },",
  "  sub: { fontSize: 14, color: '#666', marginTop: 3 },",
  "  budget: { fontSize: 14, color: '#444', marginTop: 6, fontWeight: '500' },",
  "  tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12 },",
  "  tag: { backgroundColor: '#f0eefe', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },",
  "  tagText: { fontSize: 12, color: '#534AB7', fontWeight: '500' },",
  "  bio: { fontSize: 14, color: '#555', lineHeight: 21, marginTop: 12 },",
  "  details: { marginTop: 14, borderTopWidth: 0.5, borderTopColor: '#e5e5e5', paddingTop: 12, gap: 8 },",
  "  detailRow: { flexDirection: 'row', justifyContent: 'space-between' },",
  "  detailLabel: { fontSize: 13, color: '#888' },",
  "  detailValue: { fontSize: 13, color: '#333', fontWeight: '500' },",
  "});",
].join('\n'));

console.log('\nReal feed wired in! Run: npx expo start --clear');
