const fs = require('fs');
const path = require('path');

function write(filePath, content) {
  const dir = path.dirname(filePath);
  if (dir !== '.') fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Created: ' + filePath);
}

// Supabase client
write('src/lib/supabase.js', [
  "import { createClient } from '@supabase/supabase-js';",
  "",
  "const SUPABASE_URL = 'https://uwgmkazkusuvwyfhtpuu.supabase.co';",
  "const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3Z21rYXprdXN1dnd5Zmh0cHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwNjg3NzUsImV4cCI6MjA5NDY0NDc3NX0.u3SIFeaI03NIPqSq6YG3C4sK3lTRWrF_qhXmWmmp3S4';",
  "",
  "export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);",
].join('\n'));

// Auth screen (sign up + sign in)
write('src/screens/AuthScreen.js', [
  "import React, { useState } from 'react';",
  "import { View, Text, TextInput, TouchableOpacity, StyleSheet, ActivityIndicator, KeyboardAvoidingView, Platform } from 'react-native';",
  "import { supabase } from '../lib/supabase';",
  "",
  "export default function AuthScreen({ onAuth }) {",
  "  const [mode, setMode] = useState('signin');",
  "  const [email, setEmail] = useState('');",
  "  const [password, setPassword] = useState('');",
  "  const [loading, setLoading] = useState(false);",
  "  const [error, setError] = useState('');",
  "",
  "  const handleSubmit = async () => {",
  "    setLoading(true);",
  "    setError('');",
  "    try {",
  "      let result;",
  "      if (mode === 'signup') {",
  "        result = await supabase.auth.signUp({ email, password });",
  "      } else {",
  "        result = await supabase.auth.signInWithPassword({ email, password });",
  "      }",
  "      if (result.error) throw result.error;",
  "      onAuth(result.data.user);",
  "    } catch (e) {",
  "      setError(e.message);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  return (",
  "    <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>",
  "      <Text style={styles.logo}>🏠</Text>",
  "      <Text style={styles.title}>RoomieMatch</Text>",
  "      <Text style={styles.subtitle}>{mode === 'signup' ? 'Create your account' : 'Welcome back'}</Text>",
  "",
  "      <View style={styles.form}>",
  "        <TextInput style={styles.input} placeholder='Email' placeholderTextColor='#aaa' value={email} onChangeText={setEmail} autoCapitalize='none' keyboardType='email-address' />",
  "        <TextInput style={styles.input} placeholder='Password' placeholderTextColor='#aaa' value={password} onChangeText={setPassword} secureTextEntry />",
  "        {error ? <Text style={styles.error}>{error}</Text> : null}",
  "        <TouchableOpacity style={styles.btn} onPress={handleSubmit} disabled={loading}>",
  "          {loading ? <ActivityIndicator color='#fff' /> : <Text style={styles.btnText}>{mode === 'signup' ? 'Sign Up' : 'Sign In'}</Text>}",
  "        </TouchableOpacity>",
  "        <TouchableOpacity onPress={() => setMode(mode === 'signup' ? 'signin' : 'signup')}>",
  "          <Text style={styles.toggle}>{mode === 'signup' ? 'Already have an account? Sign in' : 'No account? Sign up'}</Text>",
  "        </TouchableOpacity>",
  "      </View>",
  "    </KeyboardAvoidingView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff', alignItems: 'center', justifyContent: 'center', padding: 24 },",
  "  logo: { fontSize: 64, marginBottom: 12 },",
  "  title: { fontSize: 28, fontWeight: '700', color: '#534AB7', marginBottom: 6 },",
  "  subtitle: { fontSize: 16, color: '#666', marginBottom: 32 },",
  "  form: { width: '100%', gap: 12 },",
  "  input: { backgroundColor: '#fff', borderRadius: 12, padding: 16, fontSize: 16, color: '#1a1a1a', borderWidth: 0.5, borderColor: '#e0e0e0' },",
  "  btn: { backgroundColor: '#534AB7', borderRadius: 12, padding: 16, alignItems: 'center', marginTop: 4 },",
  "  btnText: { color: '#fff', fontSize: 16, fontWeight: '600' },",
  "  toggle: { textAlign: 'center', color: '#534AB7', fontSize: 14, marginTop: 8 },",
  "  error: { color: '#E24B4A', fontSize: 13, textAlign: 'center' },",
  "});",
].join('\n'));

// Supabase profile hook
write('src/hooks/useProfile.js', [
  "import { useState, useEffect } from 'react';",
  "import { supabase } from '../lib/supabase';",
  "",
  "export default function useProfile(userId) {",
  "  const [profile, setProfile] = useState(null);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    if (!userId) return;",
  "    supabase.from('profiles').select('*').eq('id', userId).single()",
  "      .then(({ data }) => { setProfile(data); setLoading(false); });",
  "  }, [userId]);",
  "",
  "  const saveProfile = async (profileData) => {",
  "    const { data, error } = await supabase.from('profiles').upsert({ id: userId, ...profileData }).select().single();",
  "    if (!error) setProfile(data);",
  "    return { data, error };",
  "  };",
  "",
  "  return { profile, loading, saveProfile };",
  "}",
].join('\n'));

// Updated app/index.tsx with full auth + onboarding + supabase flow
write('app/index.tsx', [
  "import { useState, useEffect } from 'react';",
  "import { View, ActivityIndicator } from 'react-native';",
  "import { supabase } from '../src/lib/supabase';",
  "import AuthScreen from '../src/screens/AuthScreen';",
  "import OnboardingScreen from '../src/screens/OnboardingScreen';",
  "import TabNavigator from '../src/navigation/TabNavigator';",
  "",
  "export default function Index() {",
  "  const [user, setUser] = useState(null);",
  "  const [profile, setProfile] = useState(null);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    supabase.auth.getSession().then(({ data: { session } }) => {",
  "      setUser(session?.user ?? null);",
  "      if (session?.user) loadProfile(session.user.id);",
  "      else setLoading(false);",
  "    });",
  "    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {",
  "      setUser(session?.user ?? null);",
  "      if (session?.user) loadProfile(session.user.id);",
  "      else { setProfile(null); setLoading(false); }",
  "    });",
  "    return () => subscription.unsubscribe();",
  "  }, []);",
  "",
  "  const loadProfile = async (userId) => {",
  "    const { data } = await supabase.from('profiles').select('*').eq('id', userId).single();",
  "    setProfile(data);",
  "    setLoading(false);",
  "  };",
  "",
  "  const handleOnboardingComplete = async (profileData) => {",
  "    const { data } = await supabase.from('profiles').upsert({ id: user.id, ...profileData }).select().single();",
  "    setProfile(data);",
  "  };",
  "",
  "  if (loading) {",
  "    return <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f7ff' }}><ActivityIndicator size='large' color='#534AB7' /></View>;",
  "  }",
  "",
  "  if (!user) return <AuthScreen onAuth={(u) => setUser(u)} />;",
  "  if (!profile) return <OnboardingScreen onComplete={handleOnboardingComplete} />;",
  "  return <TabNavigator userProfile={profile} />;",
  "}",
].join('\n'));

console.log('\nSupabase wired in! Now run:');
console.log('npx expo install @supabase/supabase-js @react-native-async-storage/async-storage');
console.log('then: npx expo start --clear');
