const fs = require('fs');

fs.writeFileSync('src/screens/ChatScreen.js', [
  "import React, { useState, useEffect, useRef } from 'react';",
  "import { View, Text, StyleSheet, FlatList, TextInput, TouchableOpacity, KeyboardAvoidingView, Platform, ActivityIndicator } from 'react-native';",
  "import { supabase } from '../lib/supabase';",
  "",
  "export default function ChatScreen({ profile, currentUser, matchId, onBack }) {",
  "  const [messages, setMessages] = useState([]);",
  "  const [input, setInput] = useState('');",
  "  const [loading, setLoading] = useState(true);",
  "  const flatListRef = useRef(null);",
  "  const intervalRef = useRef(null);",
  "",
  "  useEffect(() => {",
  "    console.log('ChatScreen opened - matchId:', matchId, 'currentUser:', currentUser?.id, 'profile:', profile?.name);",
  "    loadMessages();",
  "    intervalRef.current = setInterval(loadMessages, 3000);",
  "    return () => clearInterval(intervalRef.current);",
  "  }, [matchId]);",
  "",
  "  const loadMessages = async () => {",
  "    console.log('Loading messages for matchId:', matchId);",
  "    const { data, error } = await supabase",
  "      .from('messages')",
  "      .select('*')",
  "      .eq('match_id', matchId)",
  "      .order('created_at', { ascending: true });",
  "    console.log('Messages loaded:', data?.length, 'Error:', error);",
  "    if (error) return;",
  "    setMessages(data || []);",
  "    setLoading(false);",
  "  };",
  "",
  "  const sendMessage = async () => {",
  "    if (!input.trim()) return;",
  "    const text = input.trim();",
  "    setInput('');",
  "    const { error } = await supabase",
  "      .from('messages')",
  "      .insert({ match_id: matchId, sender_id: currentUser.id, text });",
  "    if (error) { console.log('Error sending message:', error); return; }",
  "    loadMessages();",
  "  };",
  "",
  "  return (",
  "    <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>",
  "      <View style={styles.header}>",
  "        <TouchableOpacity onPress={onBack} style={styles.backBtn}>",
  "          <Text style={styles.backText}>Back</Text>",
  "        </TouchableOpacity>",
  "        <View style={[styles.headerAvatar, { backgroundColor: profile.color || '#EEEDFE' }]}>",
  "          <Text style={styles.headerEmoji}>{profile.emoji || '🧑'}</Text>",
  "        </View>",
  "        <View>",
  "          <Text style={styles.headerName}>{profile.name}</Text>",
  "          <Text style={styles.headerSub}>{profile.location}</Text>",
  "        </View>",
  "      </View>",
  "      {loading ? <ActivityIndicator style={{ flex: 1 }} color='#534AB7' /> : (",
  "        <FlatList",
  "          ref={flatListRef}",
  "          data={messages}",
  "          keyExtractor={item => item.id}",
  "          contentContainerStyle={styles.messageList}",
  "          onContentSizeChange={() => flatListRef.current?.scrollToEnd({ animated: true })}",
  "          renderItem={({ item }) => {",
  "            const isMe = item.sender_id === currentUser.id;",
  "            return (",
  "              <View style={[styles.messageBubble, isMe ? styles.myBubble : styles.theirBubble]}>",
  "                <Text style={[styles.messageText, isMe ? styles.myText : styles.theirText]}>{item.text}</Text>",
  "                <Text style={[styles.timeText, !isMe && { color: '#999' }]}>",
  "                  {new Date(item.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}",
  "                </Text>",
  "              </View>",
  "            );",
  "          }}",
  "        />",
  "      )}",
  "      <View style={styles.inputRow}>",
  "        <TextInput",
  "          style={styles.input}",
  "          value={input}",
  "          onChangeText={setInput}",
  "          placeholder='Message...'",
  "          placeholderTextColor='#aaa'",
  "          returnKeyType='send'",
  "          onSubmitEditing={sendMessage}",
  "        />",
  "        <TouchableOpacity style={styles.sendBtn} onPress={sendMessage}>",
  "          <Text style={styles.sendText}>Send</Text>",
  "        </TouchableOpacity>",
  "      </View>",
  "    </KeyboardAvoidingView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  header: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, backgroundColor: '#fff', borderBottomWidth: 0.5, borderBottomColor: '#e5e5e5' },",
  "  backBtn: { marginRight: 4 },",
  "  backText: { fontSize: 16, color: '#534AB7', fontWeight: '500' },",
  "  headerAvatar: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },",
  "  headerEmoji: { fontSize: 20 },",
  "  headerName: { fontSize: 16, fontWeight: '600', color: '#1a1a1a' },",
  "  headerSub: { fontSize: 12, color: '#888' },",
  "  messageList: { padding: 16, gap: 10 },",
  "  messageBubble: { maxWidth: '75%', padding: 12, borderRadius: 18, gap: 4 },",
  "  myBubble: { backgroundColor: '#534AB7', alignSelf: 'flex-end', borderBottomRightRadius: 4 },",
  "  theirBubble: { backgroundColor: '#fff', alignSelf: 'flex-start', borderBottomLeftRadius: 4, borderWidth: 0.5, borderColor: '#e5e5e5' },",
  "  messageText: { fontSize: 15, lineHeight: 21 },",
  "  myText: { color: '#fff' },",
  "  theirText: { color: '#1a1a1a' },",
  "  timeText: { fontSize: 10, color: 'rgba(255,255,255,0.6)', alignSelf: 'flex-end' },",
  "  inputRow: { flexDirection: 'row', gap: 10, padding: 12, paddingBottom: 32, backgroundColor: '#fff', borderTopWidth: 0.5, borderTopColor: '#e5e5e5' },",
  "  input: { flex: 1, backgroundColor: '#f5f5f5', borderRadius: 24, paddingHorizontal: 16, paddingVertical: 10, fontSize: 15, color: '#1a1a1a' },",
  "  sendBtn: { backgroundColor: '#534AB7', borderRadius: 24, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center' },",
  "  sendText: { color: '#fff', fontWeight: '600', fontSize: 14 },",
  "});",
].join('\n'), 'utf8');

console.log('Debug logs added! Run: npx expo start --clear');
