const fs = require('fs');

fs.writeFileSync('src/hooks/useProfiles.js', [
  "import { useState, useEffect, useCallback } from 'react';",
  "import { supabase } from '../lib/supabase';",
  "",
  "export default function useProfiles(currentUserId, refreshTrigger) {",
  "  const [profiles, setProfiles] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    if (!currentUserId) { setLoading(false); return; }",
  "    fetchProfiles();",
  "  }, [currentUserId, refreshTrigger]);",
  "",
  "  const fetchProfiles = async () => {",
  "    // Get already matched user IDs",
  "    const { data: matchData } = await supabase",
  "      .from('matches')",
  "      .select('matched_user_id, user_id')",
  "      .or('user_id.eq.' + currentUserId + ',matched_user_id.eq.' + currentUserId);",
  "",
  "    const matchedIds = new Set();",
  "    (matchData || []).forEach(m => {",
  "      if (m.user_id !== currentUserId) matchedIds.add(m.user_id);",
  "      if (m.matched_user_id !== currentUserId) matchedIds.add(m.matched_user_id);",
  "    });",
  "",
  "    console.log('Excluding matched IDs:', [...matchedIds]);",
  "",
  "    let query = supabase.from('profiles').select('*').neq('id', currentUserId);",
  "    if (matchedIds.size > 0) {",
  "      query = query.not('id', 'in', '(' + [...matchedIds].join(',') + ')');",
  "    }",
  "    const { data, error } = await query;",
  "    if (error) console.log('Error fetching profiles:', error);",
  "    setProfiles(data || []);",
  "    setLoading(false);",
  "  };",
  "",
  "  return { profiles, loading };",
  "}",
].join('\n'), 'utf8');
console.log('Fixed useProfiles.js');

fs.writeFileSync('src/screens/DiscoverScreen.js', [
  "import React, { useState, useRef } from 'react';",
  "import { View, Text, StyleSheet, Animated, PanResponder, TouchableOpacity, Dimensions, ActivityIndicator } from 'react-native';",
  "import ProfileCard from '../components/ProfileCard';",
  "import useProfiles from '../hooks/useProfiles';",
  "",
  "const SCREEN_WIDTH = Dimensions.get('window').width;",
  "const SWIPE_THRESHOLD = SCREEN_WIDTH * 0.25;",
  "",
  "export default function DiscoverScreen({ onMatch, userProfile }) {",
  "  const [currentIndex, setCurrentIndex] = useState(0);",
  "  const [refreshTrigger, setRefreshTrigger] = useState(0);",
  "  const { profiles, loading } = useProfiles(userProfile?.id, refreshTrigger);",
  "  const position = useRef(new Animated.ValueXY()).current;",
  "",
  "  const panResponder = PanResponder.create({",
  "    onStartShouldSetPanResponder: () => true,",
  "    onPanResponderMove: (_, gesture) => { position.setValue({ x: gesture.dx, y: gesture.dy }); },",
  "    onPanResponderRelease: (_, gesture) => {",
  "      if (gesture.dx > SWIPE_THRESHOLD) swipeRight();",
  "      else if (gesture.dx < -SWIPE_THRESHOLD) swipeLeft();",
  "      else Animated.spring(position, { toValue: { x: 0, y: 0 }, useNativeDriver: false }).start();",
  "    },",
  "  });",
  "",
  "  const swipeRight = () => {",
  "    Animated.timing(position, { toValue: { x: SCREEN_WIDTH * 1.5, y: 0 }, duration: 300, useNativeDriver: false }).start(() => {",
  "      onMatch(profiles[currentIndex]);",
  "      nextCard(true);",
  "    });",
  "  };",
  "",
  "  const swipeLeft = () => {",
  "    Animated.timing(position, { toValue: { x: -SCREEN_WIDTH * 1.5, y: 0 }, duration: 300, useNativeDriver: false }).start(() => nextCard(false));",
  "  };",
  "",
  "  const nextCard = (wasMatch) => {",
  "    position.setValue({ x: 0, y: 0 });",
  "    if (wasMatch) {",
  "      // Refetch profiles to exclude the one just matched",
  "      setRefreshTrigger(t => t + 1);",
  "      setCurrentIndex(0);",
  "    } else {",
  "      setCurrentIndex(i => i + 1);",
  "    }",
  "  };",
  "",
  "  const rotate = position.x.interpolate({ inputRange: [-SCREEN_WIDTH / 2, 0, SCREEN_WIDTH / 2], outputRange: ['-10deg', '0deg', '10deg'], extrapolate: 'clamp' });",
  "  const likeOpacity = position.x.interpolate({ inputRange: [0, SWIPE_THRESHOLD], outputRange: [0, 1], extrapolate: 'clamp' });",
  "  const nopeOpacity = position.x.interpolate({ inputRange: [-SWIPE_THRESHOLD, 0], outputRange: [1, 0], extrapolate: 'clamp' });",
  "",
  "  if (loading) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <ActivityIndicator size='large' color='#534AB7' />",
  "        <Text style={styles.emptySub}>Finding roommates...</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  if (profiles.length === 0) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <Text style={styles.emptyTitle}>No roommates yet!</Text>",
  "        <Text style={styles.emptySub}>Share the app with friends to see profiles here.</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  if (currentIndex >= profiles.length) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <Text style={styles.emptyTitle}>You have seen everyone!</Text>",
  "        <Text style={styles.emptySub}>Check your matches tab</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <Text style={styles.header}>RoomieMatch</Text>",
  "      <View style={styles.cardContainer}>",
  "        {currentIndex + 1 < profiles.length && (",
  "          <View style={[styles.cardWrapper, styles.backCard]}>",
  "            <ProfileCard profile={profiles[currentIndex + 1]} userProfile={userProfile} />",
  "          </View>",
  "        )}",
  "        <Animated.View style={[styles.cardWrapper, { transform: [{ translateX: position.x }, { translateY: position.y }, { rotate }] }]} {...panResponder.panHandlers}>",
  "          <Animated.View style={[styles.stamp, styles.likeStamp, { opacity: likeOpacity }]}><Text style={styles.likeText}>LIKE</Text></Animated.View>",
  "          <Animated.View style={[styles.stamp, styles.nopeStamp, { opacity: nopeOpacity }]}><Text style={styles.nopeText}>NOPE</Text></Animated.View>",
  "          <ProfileCard profile={profiles[currentIndex]} userProfile={userProfile} />",
  "        </Animated.View>",
  "      </View>",
  "      <View style={styles.actions}>",
  "        <TouchableOpacity style={[styles.btn, styles.passBtn]} onPress={swipeLeft}><Text style={styles.passBtnText}>X</Text></TouchableOpacity>",
  "        <TouchableOpacity style={[styles.btn, styles.likeBtn]} onPress={swipeRight}><Text style={styles.likeBtnText}>Like</Text></TouchableOpacity>",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  header: { fontSize: 22, fontWeight: '700', color: '#534AB7', textAlign: 'center', paddingTop: 56, paddingBottom: 12 },",
  "  cardContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },",
  "  cardWrapper: { position: 'absolute', width: '100%' },",
  "  backCard: { transform: [{ scale: 0.95 }, { translateY: 12 }] },",
  "  stamp: { position: 'absolute', top: 24, zIndex: 10, paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8, borderWidth: 3 },",
  "  likeStamp: { left: 20, borderColor: '#1D9E75', backgroundColor: 'rgba(29,158,117,0.1)' },",
  "  likeText: { fontSize: 22, fontWeight: '800', color: '#1D9E75', letterSpacing: 2 },",
  "  nopeStamp: { right: 20, borderColor: '#E24B4A', backgroundColor: 'rgba(226,75,74,0.1)' },",
  "  nopeText: { fontSize: 22, fontWeight: '800', color: '#E24B4A', letterSpacing: 2 },",
  "  actions: { flexDirection: 'row', justifyContent: 'center', gap: 24, paddingVertical: 20, paddingBottom: 32 },",
  "  btn: { width: 60, height: 60, borderRadius: 30, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 3 },",
  "  passBtn: { backgroundColor: '#fff', borderWidth: 0.5, borderColor: '#ddd' },",
  "  passBtnText: { fontSize: 20, color: '#E24B4A', fontWeight: '700' },",
  "  likeBtn: { backgroundColor: '#f0eefe', borderWidth: 0.5, borderColor: '#AFA9EC' },",
  "  likeBtnText: { fontSize: 16, color: '#534AB7', fontWeight: '700' },",
  "  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f7ff', gap: 10, padding: 32 },",
  "  emptyTitle: { fontSize: 20, fontWeight: '600', color: '#1a1a1a', textAlign: 'center' },",
  "  emptySub: { fontSize: 14, color: '#888', textAlign: 'center' },",
  "});",
].join('\n'), 'utf8');
console.log('Fixed DiscoverScreen.js');

console.log('\nAll done! App will reload automatically.');
