const fs = require('fs');

function write(filePath, content) {
  const dir = require('path').dirname(filePath);
  require('fs').mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Created: ' + filePath);
}

// Fix useProfiles to exclude already matched profiles
write('src/hooks/useProfiles.js', [
  "import { useState, useEffect } from 'react';",
  "import { supabase } from '../lib/supabase';",
  "",
  "export default function useProfiles(currentUserId) {",
  "  const [profiles, setProfiles] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    if (!currentUserId) { setLoading(false); return; }",
  "    fetchProfiles();",
  "  }, [currentUserId]);",
  "",
  "  const fetchProfiles = async () => {",
  "    // Get already matched user IDs",
  "    const { data: matchData } = await supabase",
  "      .from('matches')",
  "      .select('matched_user_id')",
  "      .eq('user_id', currentUserId);",
  "    const matchedIds = (matchData || []).map(m => m.matched_user_id);",
  "",
  "    // Fetch profiles excluding self and already matched",
  "    let query = supabase.from('profiles').select('*').neq('id', currentUserId);",
  "    if (matchedIds.length > 0) {",
  "      query = query.not('id', 'in', '(' + matchedIds.join(',') + ')');",
  "    }",
  "    const { data, error } = await query;",
  "    if (error) console.log('Error fetching profiles:', error);",
  "    setProfiles(data || []);",
  "    setLoading(false);",
  "  };",
  "",
  "  return { profiles, loading };",
  "}",
].join('\n'));

// Updated ChatScreen that saves and loads messages from Supabase
write('src/screens/ChatScreen.js', [
  "import React, { useState, useEffect } from 'react';",
  "import { View, Text, StyleSheet, FlatList, TextInput, TouchableOpacity, KeyboardAvoidingView, Platform, ActivityIndicator } from 'react-native';",
  "import { supabase } from '../lib/supabase';",
  "",
  "export default function ChatScreen({ profile, currentUser, matchId, onBack }) {",
  "  const [messages, setMessages] = useState([]);",
  "  const [input, setInput] = useState('');",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    loadMessages();",
  "  }, [matchId]);",
  "",
  "  const loadMessages = async () => {",
  "    const { data, error } = await supabase",
  "      .from('messages')",
  "      .select('*')",
  "      .eq('match_id', matchId)",
  "      .order('created_at', { ascending: true });",
  "    if (error) console.log('Error loading messages:', error);",
  "    setMessages(data || []);",
  "    setLoading(false);",
  "  };",
  "",
  "  const sendMessage = async () => {",
  "    if (!input.trim()) return;",
  "    const text = input.trim();",
  "    setInput('');",
  "    const { data, error } = await supabase",
  "      .from('messages')",
  "      .insert({ match_id: matchId, sender_id: currentUser.id, text })",
  "      .select()",
  "      .single();",
  "    if (error) { console.log('Error sending message:', error); return; }",
  "    setMessages(prev => [...prev, data]);",
  "  };",
  "",
  "  return (",
  "    <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>",
  "      <View style={styles.header}>",
  "        <TouchableOpacity onPress={onBack} style={styles.backBtn}>",
  "          <Text style={styles.backText}>Back</Text>",
  "        </TouchableOpacity>",
  "        <View style={[styles.headerAvatar, { backgroundColor: profile.color || '#EEEDFE' }]}>",
  "          <Text style={styles.headerEmoji}>{profile.emoji || '🧑'}</Text>",
  "        </View>",
  "        <View>",
  "          <Text style={styles.headerName}>{profile.name}</Text>",
  "          <Text style={styles.headerSub}>{profile.location}</Text>",
  "        </View>",
  "      </View>",
  "      {loading ? <ActivityIndicator style={{ flex: 1 }} color='#534AB7' /> : (",
  "        <FlatList",
  "          data={messages}",
  "          keyExtractor={item => item.id}",
  "          contentContainerStyle={styles.messageList}",
  "          renderItem={({ item }) => {",
  "            const isMe = item.sender_id === currentUser.id;",
  "            return (",
  "              <View style={[styles.messageBubble, isMe ? styles.myBubble : styles.theirBubble]}>",
  "                <Text style={[styles.messageText, isMe ? styles.myText : styles.theirText]}>{item.text}</Text>",
  "                <Text style={[styles.timeText, !isMe && { color: '#999' }]}>",
  "                  {new Date(item.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}",
  "                </Text>",
  "              </View>",
  "            );",
  "          }}",
  "        />",
  "      )}",
  "      <View style={styles.inputRow}>",
  "        <TextInput",
  "          style={styles.input}",
  "          value={input}",
  "          onChangeText={setInput}",
  "          placeholder='Message...'",
  "          placeholderTextColor='#aaa'",
  "          returnKeyType='send'",
  "          onSubmitEditing={sendMessage}",
  "        />",
  "        <TouchableOpacity style={styles.sendBtn} onPress={sendMessage}>",
  "          <Text style={styles.sendText}>Send</Text>",
  "        </TouchableOpacity>",
  "      </View>",
  "    </KeyboardAvoidingView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  header: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, backgroundColor: '#fff', borderBottomWidth: 0.5, borderBottomColor: '#e5e5e5' },",
  "  backBtn: { marginRight: 4 },",
  "  backText: { fontSize: 16, color: '#534AB7', fontWeight: '500' },",
  "  headerAvatar: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },",
  "  headerEmoji: { fontSize: 20 },",
  "  headerName: { fontSize: 16, fontWeight: '600', color: '#1a1a1a' },",
  "  headerSub: { fontSize: 12, color: '#888' },",
  "  messageList: { padding: 16, gap: 10 },",
  "  messageBubble: { maxWidth: '75%', padding: 12, borderRadius: 18, gap: 4 },",
  "  myBubble: { backgroundColor: '#534AB7', alignSelf: 'flex-end', borderBottomRightRadius: 4 },",
  "  theirBubble: { backgroundColor: '#fff', alignSelf: 'flex-start', borderBottomLeftRadius: 4, borderWidth: 0.5, borderColor: '#e5e5e5' },",
  "  messageText: { fontSize: 15, lineHeight: 21 },",
  "  myText: { color: '#fff' },",
  "  theirText: { color: '#1a1a1a' },",
  "  timeText: { fontSize: 10, color: 'rgba(255,255,255,0.6)', alignSelf: 'flex-end' },",
  "  inputRow: { flexDirection: 'row', gap: 10, padding: 12, paddingBottom: 32, backgroundColor: '#fff', borderTopWidth: 0.5, borderTopColor: '#e5e5e5' },",
  "  input: { flex: 1, backgroundColor: '#f5f5f5', borderRadius: 24, paddingHorizontal: 16, paddingVertical: 10, fontSize: 15, color: '#1a1a1a' },",
  "  sendBtn: { backgroundColor: '#534AB7', borderRadius: 24, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center' },",
  "  sendText: { color: '#fff', fontWeight: '600', fontSize: 14 },",
  "});",
].join('\n'));

// Updated MatchesScreen to pass matchId and currentUser to ChatScreen
write('src/screens/MatchesScreen.js', [
  "import React, { useState } from 'react';",
  "import { View, Text, FlatList, StyleSheet, TouchableOpacity } from 'react-native';",
  "import ChatScreen from './ChatScreen';",
  "",
  "export default function MatchesScreen({ matches, currentUser }) {",
  "  const [activeChat, setActiveChat] = useState(null);",
  "",
  "  if (activeChat) {",
  "    return (",
  "      <ChatScreen",
  "        profile={activeChat.profile}",
  "        currentUser={currentUser}",
  "        matchId={activeChat.matchId}",
  "        onBack={() => setActiveChat(null)}",
  "      />",
  "    );",
  "  }",
  "",
  "  if (matches.length === 0) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <Text style={styles.emptyTitle}>No matches yet</Text>",
  "        <Text style={styles.emptySub}>Start swiping to find your roommate</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <Text style={styles.header}>Matches</Text>",
  "      <FlatList data={matches} keyExtractor={(item) => item.profile.id} contentContainerStyle={styles.list}",
  "        renderItem={({ item }) => (",
  "          <TouchableOpacity style={styles.matchItem} activeOpacity={0.7} onPress={() => setActiveChat(item)}>",
  "            <View style={[styles.avatar, { backgroundColor: item.profile.color || '#EEEDFE' }]}>",
  "              <Text style={styles.avatarEmoji}>{item.profile.emoji || '🧑'}</Text>",
  "            </View>",
  "            <View style={styles.info}>",
  "              <View style={styles.nameRow}>",
  "                <Text style={styles.name}>{item.profile.name}</Text>",
  "                <View style={styles.badge}><Text style={styles.badgeText}>Matched</Text></View>",
  "              </View>",
  "              <Text style={styles.sub}>{item.profile.role}</Text>",
  "              <Text style={styles.sub}>{item.profile.location} - {item.profile.budget}</Text>",
  "            </View>",
  "            <Text style={styles.arrow}>›</Text>",
  "          </TouchableOpacity>",
  "        )}",
  "      />",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  header: { fontSize: 22, fontWeight: '700', color: '#534AB7', paddingTop: 56, paddingBottom: 16, paddingHorizontal: 20 },",
  "  list: { paddingHorizontal: 16, gap: 10 },",
  "  matchItem: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16, padding: 14, alignItems: 'center', gap: 14, borderWidth: 0.5, borderColor: '#e8e8e8' },",
  "  avatar: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },",
  "  avatarEmoji: { fontSize: 26 },",
  "  info: { flex: 1, gap: 3 },",
  "  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },",
  "  name: { fontSize: 16, fontWeight: '600', color: '#1a1a1a' },",
  "  badge: { backgroundColor: '#EEEDFE', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },",
  "  badgeText: { fontSize: 11, color: '#534AB7', fontWeight: '500' },",
  "  sub: { fontSize: 13, color: '#666' },",
  "  arrow: { fontSize: 22, color: '#ccc' },",
  "  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f7ff', gap: 10 },",
  "  emptyTitle: { fontSize: 20, fontWeight: '600', color: '#1a1a1a' },",
  "  emptySub: { fontSize: 14, color: '#888' },",
  "});",
].join('\n'));

// Updated TabNavigator to pass matchId and currentUser
write('src/navigation/TabNavigator.js', [
  "import React, { useState, useEffect } from 'react';",
  "import { View, TouchableOpacity, Text, StyleSheet } from 'react-native';",
  "import { supabase } from '../lib/supabase';",
  "import DiscoverScreen from '../screens/DiscoverScreen';",
  "import MatchesScreen from '../screens/MatchesScreen';",
  "import ProfileScreen from '../screens/ProfileScreen';",
  "",
  "const TABS = [",
  "  { id: 'discover', label: 'Discover', icon: 'D' },",
  "  { id: 'matches', label: 'Matches', icon: 'M' },",
  "  { id: 'profile', label: 'Profile', icon: 'P' },",
  "];",
  "",
  "export default function TabNavigator({ userProfile }) {",
  "  const [activeTab, setActiveTab] = useState('discover');",
  "  const [matches, setMatches] = useState([]);",
  "",
  "  useEffect(() => {",
  "    if (!userProfile?.id) return;",
  "    loadMatches();",
  "  }, [userProfile]);",
  "",
  "  const loadMatches = async () => {",
  "    const { data, error } = await supabase",
  "      .from('matches')",
  "      .select('id, matched_user_id, profiles!matches_matched_user_id_fkey(*)')",
  "      .eq('user_id', userProfile.id);",
  "    if (error) { console.log('Error loading matches:', error); return; }",
  "    const matchList = data.map(m => ({ matchId: m.id, profile: m.profiles })).filter(m => m.profile);",
  "    setMatches(matchList);",
  "  };",
  "",
  "  const handleMatch = async (profile) => {",
  "    if (matches.find(m => m.profile.id === profile.id)) return;",
  "    const { data, error } = await supabase",
  "      .from('matches')",
  "      .insert({ user_id: userProfile.id, matched_user_id: profile.id })",
  "      .select()",
  "      .single();",
  "    if (error) { console.log('Error saving match:', error); return; }",
  "    setMatches(prev => [{ matchId: data.id, profile }, ...prev]);",
  "  };",
  "",
  "  const renderScreen = () => {",
  "    switch (activeTab) {",
  "      case 'discover': return <DiscoverScreen onMatch={handleMatch} userProfile={userProfile} />;",
  "      case 'matches': return <MatchesScreen matches={matches} currentUser={userProfile} />;",
  "      case 'profile': return <ProfileScreen userProfile={userProfile} />;",
  "    }",
  "  };",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <View style={styles.screenArea}>{renderScreen()}</View>",
  "      <View style={styles.tabBar}>",
  "        {TABS.map(tab => {",
  "          const isActive = activeTab === tab.id;",
  "          const showBadge = tab.id === 'matches' && matches.length > 0;",
  "          return (",
  "            <TouchableOpacity key={tab.id} style={styles.tab} onPress={() => setActiveTab(tab.id)} activeOpacity={0.7}>",
  "              <View style={styles.iconWrapper}>",
  "                <Text style={[styles.icon, isActive && styles.iconActive]}>{tab.icon}</Text>",
  "                {showBadge && <View style={styles.badge}><Text style={styles.badgeText}>{matches.length}</Text></View>}",
  "              </View>",
  "              <Text style={[styles.tabLabel, isActive && styles.tabLabelActive]}>{tab.label}</Text>",
  "            </TouchableOpacity>",
  "          );",
  "        })}",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  screenArea: { flex: 1 },",
  "  tabBar: { flexDirection: 'row', backgroundColor: '#fff', borderTopWidth: 0.5, borderTopColor: '#e5e5e5', paddingBottom: 20 },",
  "  tab: { flex: 1, alignItems: 'center', paddingTop: 10, paddingBottom: 4, gap: 3 },",
  "  iconWrapper: { position: 'relative' },",
  "  icon: { fontSize: 20, color: '#aaa' },",
  "  iconActive: { color: '#534AB7' },",
  "  tabLabel: { fontSize: 11, color: '#aaa' },",
  "  tabLabelActive: { color: '#534AB7', fontWeight: '500' },",
  "  badge: { position: 'absolute', top: -4, right: -8, backgroundColor: '#534AB7', borderRadius: 8, minWidth: 16, height: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 },",
  "  badgeText: { fontSize: 10, color: '#fff', fontWeight: '600' },",
  "});",
].join('\n'));

console.log('\nAll fixed! Run: npx expo start --clear');
