const fs = require('fs');

// Fix useProfiles hook
fs.writeFileSync('src/hooks/useProfiles.js', [
  "import { useState, useEffect } from 'react';",
  "import { supabase } from '../lib/supabase';",
  "",
  "export default function useProfiles(currentUserId) {",
  "  const [profiles, setProfiles] = useState([]);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    console.log('useProfiles called with userId:', currentUserId);",
  "    if (!currentUserId) {",
  "      setLoading(false);",
  "      return;",
  "    }",
  "    supabase",
  "      .from('profiles')",
  "      .select('*')",
  "      .neq('id', currentUserId)",
  "      .then(({ data, error }) => {",
  "        console.log('Profiles fetched:', data, 'Error:', error);",
  "        setProfiles(data || []);",
  "        setLoading(false);",
  "      });",
  "  }, [currentUserId]);",
  "",
  "  return { profiles, loading };",
  "}",
].join('\n'), 'utf8');
console.log('Fixed useProfiles.js');

// Fix app/index.tsx
fs.writeFileSync('app/index.tsx', [
  "import { useState, useEffect } from 'react';",
  "import { View, ActivityIndicator } from 'react-native';",
  "import { supabase } from '../src/lib/supabase';",
  "import AuthScreen from '../src/screens/AuthScreen';",
  "import OnboardingScreen from '../src/screens/OnboardingScreen';",
  "import TabNavigator from '../src/navigation/TabNavigator';",
  "",
  "export default function Index() {",
  "  const [user, setUser] = useState(null);",
  "  const [profile, setProfile] = useState(null);",
  "  const [loading, setLoading] = useState(true);",
  "",
  "  useEffect(() => {",
  "    supabase.auth.getSession().then(({ data: { session } }) => {",
  "      setUser(session?.user ?? null);",
  "      if (session?.user) loadProfile(session.user.id);",
  "      else setLoading(false);",
  "    });",
  "    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {",
  "      setUser(session?.user ?? null);",
  "      if (session?.user) loadProfile(session.user.id);",
  "      else { setProfile(null); setLoading(false); }",
  "    });",
  "    return () => subscription.unsubscribe();",
  "  }, []);",
  "",
  "  const loadProfile = async (userId) => {",
  "    console.log('Loading profile for userId:', userId);",
  "    const { data, error } = await supabase.from('profiles').select('*').eq('id', userId).single();",
  "    console.log('Loaded profile:', data, 'Error:', error);",
  "    setProfile(data);",
  "    setLoading(false);",
  "  };",
  "",
  "  const handleOnboardingComplete = async (profileData) => {",
  "    const { name, role, location, budget, lifestyle, smoking, pets, bio } = profileData;",
  "    const { data, error } = await supabase",
  "      .from('profiles')",
  "      .upsert({ id: user.id, name, role, location, budget, lifestyle, smoking, pets, bio })",
  "      .select()",
  "      .single();",
  "    if (error) { console.log('Error saving profile:', error); return; }",
  "    setProfile(data);",
  "  };",
  "",
  "  if (loading) {",
  "    return <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f7ff' }}><ActivityIndicator size='large' color='#534AB7' /></View>;",
  "  }",
  "",
  "  if (!user) return <AuthScreen onAuth={(u) => setUser(u)} />;",
  "  if (!profile) return <OnboardingScreen onComplete={handleOnboardingComplete} />;",
  "  return <TabNavigator userProfile={profile} />;",
  "}",
].join('\n'), 'utf8');
console.log('Fixed app/index.tsx');

// Fix TabNavigator
fs.writeFileSync('src/navigation/TabNavigator.js', [
  "import React, { useState } from 'react';",
  "import { View, TouchableOpacity, Text, StyleSheet } from 'react-native';",
  "import DiscoverScreen from '../screens/DiscoverScreen';",
  "import MatchesScreen from '../screens/MatchesScreen';",
  "import ProfileScreen from '../screens/ProfileScreen';",
  "",
  "const TABS = [",
  "  { id: 'discover', label: 'Discover', icon: 'D' },",
  "  { id: 'matches', label: 'Matches', icon: 'M' },",
  "  { id: 'profile', label: 'Profile', icon: 'P' },",
  "];",
  "",
  "export default function TabNavigator({ userProfile }) {",
  "  const [activeTab, setActiveTab] = useState('discover');",
  "  const [matches, setMatches] = useState([]);",
  "",
  "  const handleMatch = (profile) => {",
  "    setMatches(prev => prev.find(m => m.id === profile.id) ? prev : [profile, ...prev]);",
  "  };",
  "",
  "  const renderScreen = () => {",
  "    switch (activeTab) {",
  "      case 'discover': return <DiscoverScreen onMatch={handleMatch} userProfile={userProfile} />;",
  "      case 'matches': return <MatchesScreen matches={matches} />;",
  "      case 'profile': return <ProfileScreen userProfile={userProfile} />;",
  "    }",
  "  };",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <View style={styles.screenArea}>{renderScreen()}</View>",
  "      <View style={styles.tabBar}>",
  "        {TABS.map(tab => {",
  "          const isActive = activeTab === tab.id;",
  "          const showBadge = tab.id === 'matches' && matches.length > 0;",
  "          return (",
  "            <TouchableOpacity key={tab.id} style={styles.tab} onPress={() => setActiveTab(tab.id)} activeOpacity={0.7}>",
  "              <View style={styles.iconWrapper}>",
  "                <Text style={[styles.icon, isActive && styles.iconActive]}>{tab.icon}</Text>",
  "                {showBadge && <View style={styles.badge}><Text style={styles.badgeText}>{matches.length}</Text></View>}",
  "              </View>",
  "              <Text style={[styles.tabLabel, isActive && styles.tabLabelActive]}>{tab.label}</Text>",
  "            </TouchableOpacity>",
  "          );",
  "        })}",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  screenArea: { flex: 1 },",
  "  tabBar: { flexDirection: 'row', backgroundColor: '#fff', borderTopWidth: 0.5, borderTopColor: '#e5e5e5', paddingBottom: 20 },",
  "  tab: { flex: 1, alignItems: 'center', paddingTop: 10, paddingBottom: 4, gap: 3 },",
  "  iconWrapper: { position: 'relative' },",
  "  icon: { fontSize: 20, color: '#aaa' },",
  "  iconActive: { color: '#534AB7' },",
  "  tabLabel: { fontSize: 11, color: '#aaa' },",
  "  tabLabelActive: { color: '#534AB7', fontWeight: '500' },",
  "  badge: { position: 'absolute', top: -4, right: -8, backgroundColor: '#534AB7', borderRadius: 8, minWidth: 16, height: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 },",
  "  badgeText: { fontSize: 10, color: '#fff', fontWeight: '600' },",
  "});",
].join('\n'), 'utf8');
console.log('Fixed TabNavigator.js');

// Fix DiscoverScreen
fs.writeFileSync('src/screens/DiscoverScreen.js', [
  "import React, { useState, useRef } from 'react';",
  "import { View, Text, StyleSheet, Animated, PanResponder, TouchableOpacity, Dimensions, ActivityIndicator } from 'react-native';",
  "import ProfileCard from '../components/ProfileCard';",
  "import useProfiles from '../hooks/useProfiles';",
  "",
  "const SCREEN_WIDTH = Dimensions.get('window').width;",
  "const SWIPE_THRESHOLD = SCREEN_WIDTH * 0.25;",
  "",
  "export default function DiscoverScreen({ onMatch, userProfile }) {",
  "  const { profiles, loading } = useProfiles(userProfile?.id);",
  "  const [currentIndex, setCurrentIndex] = useState(0);",
  "  const position = useRef(new Animated.ValueXY()).current;",
  "",
  "  const panResponder = PanResponder.create({",
  "    onStartShouldSetPanResponder: () => true,",
  "    onPanResponderMove: (_, gesture) => { position.setValue({ x: gesture.dx, y: gesture.dy }); },",
  "    onPanResponderRelease: (_, gesture) => {",
  "      if (gesture.dx > SWIPE_THRESHOLD) swipeRight();",
  "      else if (gesture.dx < -SWIPE_THRESHOLD) swipeLeft();",
  "      else Animated.spring(position, { toValue: { x: 0, y: 0 }, useNativeDriver: false }).start();",
  "    },",
  "  });",
  "",
  "  const swipeRight = () => {",
  "    Animated.timing(position, { toValue: { x: SCREEN_WIDTH * 1.5, y: 0 }, duration: 300, useNativeDriver: false }).start(() => {",
  "      onMatch(profiles[currentIndex]);",
  "      nextCard();",
  "    });",
  "  };",
  "",
  "  const swipeLeft = () => {",
  "    Animated.timing(position, { toValue: { x: -SCREEN_WIDTH * 1.5, y: 0 }, duration: 300, useNativeDriver: false }).start(() => nextCard());",
  "  };",
  "",
  "  const nextCard = () => { position.setValue({ x: 0, y: 0 }); setCurrentIndex(i => i + 1); };",
  "",
  "  const rotate = position.x.interpolate({ inputRange: [-SCREEN_WIDTH / 2, 0, SCREEN_WIDTH / 2], outputRange: ['-10deg', '0deg', '10deg'], extrapolate: 'clamp' });",
  "  const likeOpacity = position.x.interpolate({ inputRange: [0, SWIPE_THRESHOLD], outputRange: [0, 1], extrapolate: 'clamp' });",
  "  const nopeOpacity = position.x.interpolate({ inputRange: [-SWIPE_THRESHOLD, 0], outputRange: [1, 0], extrapolate: 'clamp' });",
  "",
  "  if (loading) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <ActivityIndicator size='large' color='#534AB7' />",
  "        <Text style={styles.emptySub}>Finding roommates...</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  if (profiles.length === 0) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <Text style={styles.emptyTitle}>No roommates yet!</Text>",
  "        <Text style={styles.emptySub}>Share the app with friends to see profiles here.</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  if (currentIndex >= profiles.length) {",
  "    return (",
  "      <View style={styles.emptyContainer}>",
  "        <Text style={styles.emptyTitle}>You have seen everyone!</Text>",
  "        <Text style={styles.emptySub}>Check your matches tab</Text>",
  "      </View>",
  "    );",
  "  }",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <Text style={styles.header}>RoomieMatch</Text>",
  "      <View style={styles.cardContainer}>",
  "        {currentIndex + 1 < profiles.length && (",
  "          <View style={[styles.cardWrapper, styles.backCard]}>",
  "            <ProfileCard profile={profiles[currentIndex + 1]} userProfile={userProfile} />",
  "          </View>",
  "        )}",
  "        <Animated.View style={[styles.cardWrapper, { transform: [{ translateX: position.x }, { translateY: position.y }, { rotate }] }]} {...panResponder.panHandlers}>",
  "          <Animated.View style={[styles.stamp, styles.likeStamp, { opacity: likeOpacity }]}><Text style={styles.likeText}>LIKE</Text></Animated.View>",
  "          <Animated.View style={[styles.stamp, styles.nopeStamp, { opacity: nopeOpacity }]}><Text style={styles.nopeText}>NOPE</Text></Animated.View>",
  "          <ProfileCard profile={profiles[currentIndex]} userProfile={userProfile} />",
  "        </Animated.View>",
  "      </View>",
  "      <View style={styles.actions}>",
  "        <TouchableOpacity style={[styles.btn, styles.passBtn]} onPress={swipeLeft}><Text style={styles.passBtnText}>X</Text></TouchableOpacity>",
  "        <TouchableOpacity style={[styles.btn, styles.likeBtn]} onPress={swipeRight}><Text style={styles.likeBtnText}>Like</Text></TouchableOpacity>",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  header: { fontSize: 22, fontWeight: '700', color: '#534AB7', textAlign: 'center', paddingTop: 56, paddingBottom: 12 },",
  "  cardContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },",
  "  cardWrapper: { position: 'absolute', width: '100%' },",
  "  backCard: { transform: [{ scale: 0.95 }, { translateY: 12 }] },",
  "  stamp: { position: 'absolute', top: 24, zIndex: 10, paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8, borderWidth: 3 },",
  "  likeStamp: { left: 20, borderColor: '#1D9E75', backgroundColor: 'rgba(29,158,117,0.1)' },",
  "  likeText: { fontSize: 22, fontWeight: '800', color: '#1D9E75', letterSpacing: 2 },",
  "  nopeStamp: { right: 20, borderColor: '#E24B4A', backgroundColor: 'rgba(226,75,74,0.1)' },",
  "  nopeText: { fontSize: 22, fontWeight: '800', color: '#E24B4A', letterSpacing: 2 },",
  "  actions: { flexDirection: 'row', justifyContent: 'center', gap: 24, paddingVertical: 20, paddingBottom: 32 },",
  "  btn: { width: 60, height: 60, borderRadius: 30, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 3 },",
  "  passBtn: { backgroundColor: '#fff', borderWidth: 0.5, borderColor: '#ddd' },",
  "  passBtnText: { fontSize: 20, color: '#E24B4A', fontWeight: '700' },",
  "  likeBtn: { backgroundColor: '#f0eefe', borderWidth: 0.5, borderColor: '#AFA9EC' },",
  "  likeBtnText: { fontSize: 16, color: '#534AB7', fontWeight: '700' },",
  "  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8f7ff', gap: 10, padding: 32 },",
  "  emptyTitle: { fontSize: 20, fontWeight: '600', color: '#1a1a1a', textAlign: 'center' },",
  "  emptySub: { fontSize: 14, color: '#888', textAlign: 'center' },",
  "});",
].join('\n'), 'utf8');
console.log('Fixed DiscoverScreen.js');

console.log('\nAll fixed! Run: npx expo start --clear');
