const fs = require('fs');

fs.writeFileSync('src/screens/OnboardingScreen.js', [
  "import React, { useState } from 'react';",
  "import { View, Text, StyleSheet, TextInput, TouchableOpacity, ScrollView } from 'react-native';",
  "",
  "const STEPS = ['Welcome', 'Name', 'Role', 'Location', 'Budget', 'Lifestyle', 'Bio'];",
  "",
  "export default function OnboardingScreen({ onComplete }) {",
  "  const [step, setStep] = useState(0);",
  "  const [profile, setProfile] = useState({",
  "    name: '', role: '', location: '', budget: '', lifestyle: 'Flexible', smoking: 'Non-smoker', pets: 'No preference', bio: '',",
  "  });",
  "",
  "  const update = (key, value) => setProfile(prev => ({ ...prev, [key]: value }));",
  "",
  "  const next = () => {",
  "    if (step < STEPS.length - 1) setStep(s => s + 1);",
  "    else onComplete({ name: profile.name, role: profile.role, location: profile.location, budget: profile.budget, lifestyle: profile.lifestyle, smoking: profile.smoking, pets: profile.pets, bio: profile.bio });",
  "  };",
  "",
  "  const back = () => setStep(s => s - 1);",
  "",
  "  const renderStep = () => {",
  "    switch (step) {",
  "      case 0: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.bigEmoji}>🏠</Text>",
  "          <Text style={styles.title}>Welcome to RoomieMatch</Text>",
  "          <Text style={styles.subtitle}>Find your perfect roommate in a few steps.</Text>",
  "        </View>",
  "      );",
  "      case 1: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>What is your name?</Text>",
  "          <TextInput style={styles.input} placeholder='Your name' placeholderTextColor='#aaa' value={profile.name} onChangeText={v => update('name', v)} autoFocus />",
  "        </View>",
  "      );",
  "      case 2: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>What do you do?</Text>",
  "          <TextInput style={styles.input} placeholder='e.g. Software Engineer, Student' placeholderTextColor='#aaa' value={profile.role} onChangeText={v => update('role', v)} autoFocus />",
  "        </View>",
  "      );",
  "      case 3: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>Where are you looking?</Text>",
  "          <TextInput style={styles.input} placeholder='e.g. Boston, MA' placeholderTextColor='#aaa' value={profile.location} onChangeText={v => update('location', v)} autoFocus />",
  "        </View>",
  "      );",
  "      case 4: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>What is your budget?</Text>",
  "          <TextInput style={styles.input} placeholder='e.g. $1,200-$1,600/mo' placeholderTextColor='#aaa' value={profile.budget} onChangeText={v => update('budget', v)} autoFocus />",
  "        </View>",
  "      );",
  "      case 5: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>What is your lifestyle?</Text>",
  "          {['Early bird', 'Night owl', 'Flexible'].map(opt => (",
  "            <TouchableOpacity key={opt} style={[styles.optionBtn, profile.lifestyle === opt && styles.optionBtnActive]} onPress={() => update('lifestyle', opt)}>",
  "              <Text style={[styles.optionText, profile.lifestyle === opt && styles.optionTextActive]}>{opt}</Text>",
  "            </TouchableOpacity>",
  "          ))}",
  "          <Text style={[styles.title, { marginTop: 24 }]}>Smoking?</Text>",
  "          {['Non-smoker', 'Smoker', 'No preference'].map(opt => (",
  "            <TouchableOpacity key={opt} style={[styles.optionBtn, profile.smoking === opt && styles.optionBtnActive]} onPress={() => update('smoking', opt)}>",
  "              <Text style={[styles.optionText, profile.smoking === opt && styles.optionTextActive]}>{opt}</Text>",
  "            </TouchableOpacity>",
  "          ))}",
  "          <Text style={[styles.title, { marginTop: 24 }]}>Pets?</Text>",
  "          {['No preference', 'Has pets', 'No pets'].map(opt => (",
  "            <TouchableOpacity key={opt} style={[styles.optionBtn, profile.pets === opt && styles.optionBtnActive]} onPress={() => update('pets', opt)}>",
  "              <Text style={[styles.optionText, profile.pets === opt && styles.optionTextActive]}>{opt}</Text>",
  "            </TouchableOpacity>",
  "          ))}",
  "        </View>",
  "      );",
  "      case 6: return (",
  "        <View style={styles.stepContainer}>",
  "          <Text style={styles.title}>Tell people about yourself</Text>",
  "          <TextInput style={[styles.input, styles.bioInput]} placeholder='e.g. Grad student, love cooking...' placeholderTextColor='#aaa' value={profile.bio} onChangeText={v => update('bio', v)} multiline autoFocus />",
  "        </View>",
  "      );",
  "    }",
  "  };",
  "",
  "  const isNextDisabled = () => {",
  "    if (step === 1 && !profile.name.trim()) return true;",
  "    if (step === 2 && !profile.role.trim()) return true;",
  "    if (step === 3 && !profile.location.trim()) return true;",
  "    if (step === 4 && !profile.budget.trim()) return true;",
  "    return false;",
  "  };",
  "",
  "  return (",
  "    <ScrollView style={styles.container} contentContainerStyle={styles.content} keyboardShouldPersistTaps='handled'>",
  "      <View style={styles.progressRow}>",
  "        {STEPS.map((_, i) => (",
  "          <View key={i} style={[styles.progressDot, i <= step && styles.progressDotActive]} />",
  "        ))}",
  "      </View>",
  "      {renderStep()}",
  "      <View style={styles.btnRow}>",
  "        {step > 0 && (",
  "          <TouchableOpacity style={styles.backBtn} onPress={back}>",
  "            <Text style={styles.backBtnText}>Back</Text>",
  "          </TouchableOpacity>",
  "        )}",
  "        <TouchableOpacity style={[styles.nextBtn, isNextDisabled() && styles.nextBtnDisabled]} onPress={next} disabled={isNextDisabled()}>",
  "          <Text style={styles.nextBtnText}>{step === STEPS.length - 1 ? 'Get Started' : 'Next'}</Text>",
  "        </TouchableOpacity>",
  "      </View>",
  "    </ScrollView>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  content: { padding: 24, paddingTop: 60, minHeight: '100%' },",
  "  progressRow: { flexDirection: 'row', gap: 6, marginBottom: 40 },",
  "  progressDot: { flex: 1, height: 4, borderRadius: 2, backgroundColor: '#e0e0e0' },",
  "  progressDotActive: { backgroundColor: '#534AB7' },",
  "  stepContainer: { flex: 1, gap: 16 },",
  "  bigEmoji: { fontSize: 64, textAlign: 'center', marginBottom: 8 },",
  "  title: { fontSize: 24, fontWeight: '700', color: '#1a1a1a' },",
  "  subtitle: { fontSize: 16, color: '#666', lineHeight: 24 },",
  "  input: { backgroundColor: '#fff', borderRadius: 12, padding: 16, fontSize: 16, color: '#1a1a1a', borderWidth: 0.5, borderColor: '#e0e0e0' },",
  "  bioInput: { height: 120, textAlignVertical: 'top' },",
  "  optionBtn: { backgroundColor: '#fff', borderRadius: 12, padding: 16, borderWidth: 0.5, borderColor: '#e0e0e0' },",
  "  optionBtnActive: { backgroundColor: '#534AB7', borderColor: '#534AB7' },",
  "  optionText: { fontSize: 16, color: '#1a1a1a', fontWeight: '500' },",
  "  optionTextActive: { color: '#fff' },",
  "  btnRow: { flexDirection: 'row', gap: 12, marginTop: 40, paddingBottom: 40 },",
  "  backBtn: { flex: 1, padding: 16, borderRadius: 12, borderWidth: 0.5, borderColor: '#e0e0e0', alignItems: 'center' },",
  "  backBtnText: { fontSize: 16, color: '#666', fontWeight: '500' },",
  "  nextBtn: { flex: 2, padding: 16, borderRadius: 12, backgroundColor: '#534AB7', alignItems: 'center' },",
  "  nextBtnDisabled: { backgroundColor: '#ccc' },",
  "  nextBtnText: { fontSize: 16, color: '#fff', fontWeight: '600' },",
  "});",
].join('\n'), 'utf8');

console.log('Fixed! Now sign out, sign up with a second account, complete onboarding, then sign back into your original account.');
