const fs = require('fs');

function write(filePath, content) {
  const dir = require('path').dirname(filePath);
  require('fs').mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Created: ' + filePath);
}

// Updated TabNavigator - saves matches to Supabase and loads them on start
write('src/navigation/TabNavigator.js', [
  "import React, { useState, useEffect } from 'react';",
  "import { View, TouchableOpacity, Text, StyleSheet } from 'react-native';",
  "import { supabase } from '../lib/supabase';",
  "import DiscoverScreen from '../screens/DiscoverScreen';",
  "import MatchesScreen from '../screens/MatchesScreen';",
  "import ProfileScreen from '../screens/ProfileScreen';",
  "",
  "const TABS = [",
  "  { id: 'discover', label: 'Discover', icon: 'D' },",
  "  { id: 'matches', label: 'Matches', icon: 'M' },",
  "  { id: 'profile', label: 'Profile', icon: 'P' },",
  "];",
  "",
  "export default function TabNavigator({ userProfile }) {",
  "  const [activeTab, setActiveTab] = useState('discover');",
  "  const [matches, setMatches] = useState([]);",
  "",
  "  // Load existing matches from Supabase on start",
  "  useEffect(() => {",
  "    if (!userProfile?.id) return;",
  "    loadMatches();",
  "  }, [userProfile]);",
  "",
  "  const loadMatches = async () => {",
  "    const { data, error } = await supabase",
  "      .from('matches')",
  "      .select('matched_user_id, profiles!matches_matched_user_id_fkey(*)')",
  "      .eq('user_id', userProfile.id);",
  "    if (error) { console.log('Error loading matches:', error); return; }",
  "    const matchedProfiles = data.map(m => m.profiles).filter(Boolean);",
  "    setMatches(matchedProfiles);",
  "  };",
  "",
  "  const handleMatch = async (profile) => {",
  "    // Avoid duplicates locally",
  "    if (matches.find(m => m.id === profile.id)) return;",
  "    // Save to Supabase",
  "    const { error } = await supabase",
  "      .from('matches')",
  "      .insert({ user_id: userProfile.id, matched_user_id: profile.id });",
  "    if (error) { console.log('Error saving match:', error); return; }",
  "    setMatches(prev => [profile, ...prev]);",
  "  };",
  "",
  "  const renderScreen = () => {",
  "    switch (activeTab) {",
  "      case 'discover': return <DiscoverScreen onMatch={handleMatch} userProfile={userProfile} />;",
  "      case 'matches': return <MatchesScreen matches={matches} />;",
  "      case 'profile': return <ProfileScreen userProfile={userProfile} />;",
  "    }",
  "  };",
  "",
  "  return (",
  "    <View style={styles.container}>",
  "      <View style={styles.screenArea}>{renderScreen()}</View>",
  "      <View style={styles.tabBar}>",
  "        {TABS.map(tab => {",
  "          const isActive = activeTab === tab.id;",
  "          const showBadge = tab.id === 'matches' && matches.length > 0;",
  "          return (",
  "            <TouchableOpacity key={tab.id} style={styles.tab} onPress={() => setActiveTab(tab.id)} activeOpacity={0.7}>",
  "              <View style={styles.iconWrapper}>",
  "                <Text style={[styles.icon, isActive && styles.iconActive]}>{tab.icon}</Text>",
  "                {showBadge && <View style={styles.badge}><Text style={styles.badgeText}>{matches.length}</Text></View>}",
  "              </View>",
  "              <Text style={[styles.tabLabel, isActive && styles.tabLabelActive]}>{tab.label}</Text>",
  "            </TouchableOpacity>",
  "          );",
  "        })}",
  "      </View>",
  "    </View>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f8f7ff' },",
  "  screenArea: { flex: 1 },",
  "  tabBar: { flexDirection: 'row', backgroundColor: '#fff', borderTopWidth: 0.5, borderTopColor: '#e5e5e5', paddingBottom: 20 },",
  "  tab: { flex: 1, alignItems: 'center', paddingTop: 10, paddingBottom: 4, gap: 3 },",
  "  iconWrapper: { position: 'relative' },",
  "  icon: { fontSize: 20, color: '#aaa' },",
  "  iconActive: { color: '#534AB7' },",
  "  tabLabel: { fontSize: 11, color: '#aaa' },",
  "  tabLabelActive: { color: '#534AB7', fontWeight: '500' },",
  "  badge: { position: 'absolute', top: -4, right: -8, backgroundColor: '#534AB7', borderRadius: 8, minWidth: 16, height: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 3 },",
  "  badgeText: { fontSize: 10, color: '#fff', fontWeight: '600' },",
  "});",
].join('\n'));

console.log('\nMatches now save to Supabase! Run: npx expo start --clear');
